### ISSUE TITLE
the game starts larger than my display

### ISSUE THREAD

**Issue by only1thor** [Magnus2552/quickcurver#1]
the game start so large that i cant se large parts of the UI. is ther any setting to set the window size? I can't resize the window with the mouse either.

**Comment by vimpostor** [comment]
What is the resolution of your screen?
I pushed a fix to the develop branch, you should at least be able to resize the window with your mouse now.

**Comment by vimpostor** [comment]
Btw in case you meant the actual game frame and not the whole window, there is already a setting to set the size of the game frame.

**Comment by only1thor** [comment]
that last fix definitly did it! i re-downloaded and installed and now it started as a maximized window. although when i enter the game i cant see the entire game area. 
i'm on gnome 3 by the way.

**Comment by only1thor** [comment]
ok, so update, i found the "field size" and that made the game work, sort of. the background does not remove all the menu elements from the main menu. and clicking the "back" arrow exits the entire program. not just the gamefield. 
also i can't find a way to remove a player from the first menu ( but that may be better to make a new issue over?)

**Comment by vimpostor** [comment]
Yeah, a new issue would be better for that. I just pushed a commit that enables you to remove players (currently only in develop branch).
I also agree that closing the program when hitting the back arrow is very user unfriendly. I will get onto that too.
Anyways, thank you for reporting this issue. If there is anything else, don't hesitate to open up another issue. :)

**Comment by vimpostor** [comment]
Btw, what do you mean with "the background does not remove all the menu elements from the main menu"?

**Comment by only1thor** [comment]
first off, this is what the game looks like if i just start it and click play:
![screenshot from 2017-06-01 12-19-12](https://cloud.githubusercontent.com/assets/8517915/26675556/b9dafe46-46c4-11e7-9f7a-530bee5724e2.png)

and if i change the size of the play area like this:
![screenshot from 2017-06-01 12-19-27](https://cloud.githubusercontent.com/assets/8517915/26675585/ca2c52c2-46c4-11e7-80c5-13a4a667a9f0.png)

then i get the issue with the menu elements:
![screenshot from 2017-06-01 12-19-40](https://cloud.githubusercontent.com/assets/8517915/26675596/d452a594-46c4-11e7-92ee-ffe32f180e89.png)

**Comment by vimpostor** [comment]
Thank you very much for the screenshots, this really helps a lot! :)
These layout issues really have to be fixed. I am about to support Android builds too, so I have to get the layout working on any screen size anyway.

**Comment by sam9032** [comment]
Great News! Thank you for this great project.

**Comment by only1thor** [comment]
Cool, i cant wait to try the Android bulid then. :-)

**Comment by vimpostor** [comment]
I changed many things in the layout now. The layout _should_ work on all devices now. The android build is already playable, but there are some minor issues that I need to address, before I will add android build instructions.
I will merge the changes into master now, which will automatically close this issue.
If there are still issues left, feel free to reopen this issue or create another issue.
Thanks for your help :)
