### ISSUE TITLE
Is there a compiled version available

### ISSUE THREAD

**Issue by Biggerandreas** [Magnus2552/quickcurver#3]
I know that this is not an issue for most people but for the less techy people(like me) is there a compiled version available to download?

**Comment by sam9032** [comment]
Good Question,
It would be really amazing, if there is a compiled version for windows!

**Comment by vimpostor** [comment]
@Biggerandreas Sure. What operating system are you running? I was thinking about providing binaries anyway. :)

**Comment by Biggerandreas** [comment]
@magnus-gross I'm using both Raspian and Windows, thanks for the quick reply.

**Comment by sam9032** [comment]
Is there any binary now?
I tried to make one for windows, but i failed :(

**Comment by Biggerandreas** [comment]
@sam9032 Don't think so.

**Comment by vimpostor** [comment]
Sry for not keeping you updated for so long.

I just tried to make a static build, but it turns out, that there are some library issues that have to be fixed upstream first: https://github.com/lirios/fluid/issues/219

**Comment by Biggerandreas** [comment]
@magnus-gross 
It's completely fine man, good luck with it.

**Comment by vimpostor** [comment]
Hi @Biggerandreas, I know this is a bit late, but you can now download a compiled exe of the latest stable build at https://ci.appveyor.com/project/magnus-gross/quickcurver :) Just navigate to Artifacts, download the zip file, extract it and start `QuickCurver.exe` in the `release` subdirectory.

**Comment by sam9032** [comment]
It's amazing. Thank you for the great opportunity!

**Comment by vimpostor** [comment]
You are quite welcome, Mr. @sam9032
