### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by sam9032** [Magnus2552/quickcurver#5]
Hello there!
When is the next major update coming and what new features are planned?
Positional audio is just crazy man!

**Comment by vimpostor** [comment]
Hi @sam9032,

at the moment no MAJOR update is planned, I am just so busy with other projects, you know? But if you feel like there is a feature missing, feel free to post a feature request.

I know right? Positional audio is the shit, I still have a headache from the last time we used it!

P.S.: Nevertheless, there are still some things in my Not-Todo list for this project, e.g. port it away from OpenGL, as OpenGL is being deprecated on MacOS. Also I could probably fix the Arch Linux package some time in the future...

All the best and I hope you are in good health in this crisis,
Magnus!
