### ISSUE TITLE
Help, your artifact is down

### ISSUE THREAD

**Issue by sam9032** [Magnus2552/quickcurver#8]
Hello,
i want to try your game, but the link to the precompiled Windows exe seems to be broken? :-(

[the latest build artifact](https://ci.appveyor.com/api/projects/magnus-gross/quickcurver/artifacts/build%2FQuickCurver.zip)

Please fix it @vimpostor, this would be amazing :100:

**Comment by vimpostor** [comment]
Hi @sam9032, thank you very much for the bug report.
Unfortunately it looks like the AppVeyor Windows CI broke at some point, and now I am thinking of dropping Windows support entirely as it is not financially worthwhille to support such an obscure platform. :(

**Comment by vimpostor** [comment]
I think I got it working now again. Unfortunately, AppVeyor only keeps artifacts for one month now, so I should probably create an official Github release of this project and upload the artifact there.

**Comment by sam9032** [comment]
Amazing idea to create an official Github release, thank you!
Isn't it possible, to use Github actions instead of AppVeyor to compile the package?

**Comment by vimpostor** [comment]
> Isn't it possible, to use Github actions instead of AppVeyor to compile the package?

Yes, but what advantage would we have by doing this? Both are proprietary services anyway. Back when I setup the CI, Github Actions didn't exist yet and I don't see the point in wasting my time setting up another CI just for an useless Windows build.

Regards

**Comment by vimpostor** [comment]
Hi @sam9032, I have great news for you, [version 0.1](https://github.com/vimpostor/quickcurver/releases/tag/v0.1) is now published!

It also includes a precompiled Windows build, which will be permanently available on the release page.
Hope this helps, I will close this thread now.
