### ISSUE TITLE
Does QT6 support C++20 module?

### ISSUE THREAD

**Issue by tgbamg** [Magnus2552/quickcurver#9]
Could I use `import <iostream>;` and `import <QObject>;` in QT6?

**Comment by vimpostor** [comment]
Right now unfortunately both major compilers are missing complete support for modules: https://en.cppreference.com/w/cpp/compiler_support

When those compilers implement modules, it might be possible but for now we have to stick to traditional includes.

`import <iostream>` would definitely work then, but I think `import <QObject>` would require Qt code changes first.

**Comment by tgbamg** [comment]
I have tried in Qt6.3.1 and here are the conclusions:
1. `import <iostream>` works fine.
2. `import <QObject>` does not work.
3. Turning lib files(For example, a.cpp) into modules does not work.

**Comment by vimpostor** [comment]
Yeah, unfortunately modules support is still in an early stage. We will have to wait a bit, before we can start getting rid of header files in C++.

**Comment by tgbamg** [comment]
Can I use PyQt instead of Qt? Is there any reason why Qt must be used?

**Comment by vimpostor** [comment]
You can use whatever you want for your own projects. I think PyQt is easier for beginners, so if you are just starting out, I would recommend it.

But in the end, Qt with C++ is the cleaner solution, especially if you want to get any good performance in your app. I personally have never tried PyQt, so I can't comment on any additional quirks it may have.

I would recommend to always write the Gui in QML though, there is just nothing better than declarative languages for UI.

May I ask what you specifically have in mind?

**Comment by tgbamg** [comment]
I am a Qt beginner. I want to use Qt to develop desktop application and mobile application. Why QML is better than Qt Designer?

**Comment by vimpostor** [comment]
> Why QML is better than Qt Designer?

I think you can use QML in Qt Designer, so there is no problem in using Qt Designer. Though I personally just write the code directly, because it's much faster than using a GUI for me, but that's a personal preference.

**Comment by tgbamg** [comment]
Ok! I want to develop Andriod App with Qt6. Is there any tutorial?

**Comment by tgbamg** [comment]
Do I must use Qt Creator and Qt Designer to develop a Qt Application? Can I develop a Qt Application just using Vim?

**Comment by vimpostor** [comment]
> Ok! I want to develop Andriod App with Qt6. Is there any tutorial?

Yes, there is: https://www.qt.io/product/qt6/qml-book/ch01-meetqt-meet-qt





> Do I must use Qt Creator and Qt Designer to develop a Qt Application? Can I develop a Qt Application just using Vim?

No, you can just use vim, I do the same. You can very easily use any editor you want, since Qt is using cmake as build system.

**Comment by vimpostor** [comment]
Closing this issue, as it has been solved.

**Comment by tgbamg** [comment]
Is there a big difference between Qt6 and Qt5? Is it easy to upgrade a Qt5 project to a Qt6 project?

**Comment by tgbamg** [comment]
Does Qt6 support all modules that we can find in Qt 5.15?

**Comment by tgbamg** [comment]
If I want to apply for a job as a Qt developer, should I learn Qt5 or Qt6?

**Comment by vimpostor** [comment]
Look, you can find almost all the answers to your questions by doing a google search. I would recommend you to use Qt 6, as it is the latest version.

**Comment by tgbamg** [comment]
But is Qt6 mature enough? I've noticed that most companies are using Qt5, and don't plan to migrate to Qt6.

**Comment by vimpostor** [comment]
> But is Qt6 mature enough?

Yes

Other companies will eventually migrate to Qt6 too.

**Comment by tgbamg** [comment]
You make a good point. Thank you so much!

**Comment by tgbamg** [comment]
How to play your game? I used "W A S D" or "Up Down Left Right", but this straight line goes by itself and does not listen to my orders.

**Comment by vimpostor** [comment]
> How to play your game? I used "W A S D" or "Up Down Left Right", but this straight line goes by itself and does not listen to my orders.

Make sure the game field is focused by clicking on it, then "Left" and "right" should work.
